BaseUrl= "https://www.riptide-rhythm.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
Title = "Riptide Rhythm"
theme = "hermit"
# enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true 
googleAnalytics = "UA-90952706-2"
disqusShortname = "riptide-rhythm"
contentDir = "content"
publishDir = "docs"

[author]
  name = "Austin Riendeau"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Guitars, Effects Pedals & Music"
  # images = [""]
  themeColor = "#0f7ea3"

  homeSubtitle = "Guitars, Effects Pedals & Music"
  footerCopyright = ' All rights reserved'
  bgImg = "images/background2500.jpg"  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = "https://github.com/username/repository/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  # Add custom css
  customCSS = ["css/brands.css"]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/apriendeau"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/apriendeau"


[menu]

  [[menu.main]]
    name = "articles"
    url = "/post/"
    weight = 1000

  [[menu.main]]
    name = "home"
    url = "/"
    weight = -1000

